---
name: Lint
on:
    workflow_call:

jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Run ruff
       uses: astral-sh/ruff-action@v3
     - name: Run ruff format
       run: ruff format --check